Обновление проекта

diff --git a/corn b/corn
--- a/corn
+++ b/corn
@@ -5,34 +5,81 @@ set -eu
 RED='\033[0;31m'
 CIAN='\033[0;36m'
 PURPLE='\033[0;35m'
+YELLOW_FG='\033[1;33m'
 NC='\033[0m'
 
-# Ensure that there is .env file
-if [ ! -f ./.env ]; then
-	echo -e "${RED}The .env file is missing, but can be installed with:${NC} \n\n\tcp .env.example .env\n"
-	exit 1
-fi
+path=$(dirname "$(realpath $0)")
 
-set -a
-. ./.env
-set +a
+info_flag=0
+dry_run_flag=0
 
-dockerComposeFiles=("docker-compose.yaml")
-
-if [ "$APP_ENV" = "local" ]; then
-	dockerComposeFiles+=("docker-compose.dev.yaml")
-else
-	dockerComposeFiles+=("docker-compose.prod.yaml")
-fi
-
-initCommand="docker-compose "
-for i in ${dockerComposeFiles[@]}; do
-	initCommand+="-f $i "
+while [[ "$#" -gt 0 ]]; do
+	case $1 in
+		-i|--info)
+			info_flag=1;
+			shift ;;
+		--dry-run)
+			dry_run_flag=1
+			info_flag=1
+			shift ;;
+		-*|--*)
+			echo "Unknown option $1"
+			exit 1 ;;
+		*)
+			break ;;
+	esac
 done
 
-echo -e "\nUsed $CIAN${dockerComposeFiles[@]}$NC files"
+# Ensure that there is .env file
+if [ ! -f $path/.env ]; then
+	echo -e "${YELLOW_FG}(warn): ${NC}The .env file is missing, dev environment using by default\n"
+else
+	set -a
+	. $path/.env
+	set +a
+fi
+
+export USER_ID=$(id -u) GROUP_ID=$(id -g)
+
+getInitCommand() {
+	dockerComposeFiles=("docker-compose.yaml")
+
+	if [ ! -f $path/.env ] || [ "$APP_ENV" = "local" ]; then
+		dockerComposeFiles+=("docker-compose.dev.yaml")
+	else
+		dockerComposeFiles+=("docker-compose.prod.yaml")
+	fi
+
+	if [ -f $path/docker-compose.override.yaml ]; then
+		dockerComposeFiles+=("docker-compose.override.yaml")
+	fi
+
+	result="docker compose "
+	for i in ${dockerComposeFiles[@]}; do
+		result+="-f $path/$i "
+	done
+
+	echo $result
+}
+
+runOrExec() {
+	service=$1
+	result="exec"
+
+	if [ -z `docker compose ps -q $service` ] || [ -z `docker ps -q --no-trunc | grep $(docker compose ps -q $service)` ]; then
+		result="run --rm"
+	fi
+
+	echo $result
+}
+
+initCommand=$(getInitCommand)
 
 if [ $# = 0 ]; then
+	if [ $info_flag = 1 ]; then
+		echo -e "${PURPLE}${initCommand}${NC}\n"
+	fi
+
 	$initCommand
 	exit 0
 fi
@@ -41,34 +88,34 @@ command=$1
 shift 1
 
 case $command in
-	"artisan" | "art")
-		runOrExec="exec"
-		if [ -z `docker ps -q --no-trunc | grep $(docker-compose ps -q php)` ]; then
-			runOrExec="run"
-		fi
-		fullCommand="$initCommand $runOrExec php php ./artisan $@"
-	;;
-
+	"php")
+		payload="$(runOrExec php) php $@" ;;
+	"artisan" | "art" | "laravel" | "lara")
+		payload="$(runOrExec php) php php /app/artisan $@" ;;
 	"composer")
-		fullCommand="$initCommand run composer composer $@"
-	;;
-
-	"npm")
-		runOrExec="exec"
-		if [ -z `docker ps -q --no-trunc | grep $(docker-compose ps -q nodejs)` ]; then
-			runOrExec="run"
-		fi
-		fullCommand="$initCommand $runOrExec nodejs npm $@"
-	;;
-
+		payload="$(runOrExec php) php composer $@" ;;
+	"yarn")
+		payload="$(runOrExec nodejs) nodejs yarn $@" ;;
+	"npx")
+		payload="$(runOrExec nodejs) nodejs npx $@" ;;
+	"nuxi")
+		payload="$(runOrExec nodejs) nodejs npx nuxi $@" ;;
 	"ngrok")
-		fullCommand="$initCommand run ngrok http host.docker.internal:80 --region=eu"
-	;;
-
+		payload="run ngrok http host.docker.internal:80 --region=eu" ;;
+	"pint" | "pinte")
+		payload="$(runOrExec php) php ./vendor/bin/pinte $@" ;;
+	"pest")
+		payload="$(runOrExec php) php ./vendor/bin/pest $@" ;;
 	*)
-		fullCommand="$initCommand $command $@"
-	;;
+		payload="${command} $@" ;;
 esac
 
-echo -e "${PURPLE}${fullCommand}${NC}\n"
-$fullCommand
+fullCommand="${initCommand} ${payload}"
+
+if [ $info_flag = 1 ]; then
+	echo -e "${PURPLE}${fullCommand}${NC}\n"
+fi
+
+if [ $dry_run_flag = 0 ]; then
+	$fullCommand
+fi
